FROM node

# install simple http server for serving static content
RUN npm install -g http-server
# RUN npm install -g @vue/cli

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# ARG VUE_APP_CHAIN=2828
# ARG VUE_APP_PLANS=2
# ARG VUE_APP_PLAN_0_NAME=Free
# ARG VUE_APP_PLAN_0_PRICE=0
# ARG VUE_APP_PLAN_0_QUOTA=0.01
# ARG VUE_APP_PLAN_0_BASEURL="/api/free/"
# ARG VUE_APP_PLAN_0_LIMITER="0x8c5767a4D24E22208D9583aB02eE60a1bdCb0c3D"
# ARG VUE_APP_PLAN_1_NAME=Basic
# ARG VUE_APP_PLAN_1_PRICE=15
# ARG VUE_APP_PLAN_1_QUOTA=1
# ARG VUE_APP_PLAN_1_BASEURL="/api/basic/"
# ARG VUE_APP_PLAN_1_LIMITER="0xE16F81f76df4584D2Fb4313727e24612453e7156"
# ARG VUE_APP_APP_URL=http://localhost:8081

ARG VUE_APP_CHAIN
ARG VUE_APP_PLANS
ARG VUE_APP_PLAN_0_NAME
ARG VUE_APP_PLAN_0_PRICE
ARG VUE_APP_PLAN_0_QUOTA
ARG VUE_APP_PLAN_0_BASEURL
ARG VUE_APP_PLAN_0_LIMITER
ARG VUE_APP_PLAN_0_CHECKOUT_URL
ARG VUE_APP_PLAN_1_NAME
ARG VUE_APP_PLAN_1_PRICE
ARG VUE_APP_PLAN_1_QUOTA
ARG VUE_APP_PLAN_1_BASEURL
ARG VUE_APP_PLAN_1_LIMITER
ARG VUE_APP_PLAN_1_CHECKOUT_URL
ARG VUE_APP_APP_URL
ARG VUE_APP_SUPPORT_EMAIL

ENV VUE_APP_CHAIN=${VUE_APP_CHAIN} \
    VUE_APP_PLANS=${VUE_APP_PLANS} \
    VUE_APP_PLAN_0_NAME=${VUE_APP_PLAN_0_NAME} \
    VUE_APP_PLAN_0_PRICE=${VUE_APP_PLAN_0_PRICE} \
    VUE_APP_PLAN_0_QUOTA=${VUE_APP_PLAN_0_QUOTA} \
    VUE_APP_PLAN_0_BASEURL=${VUE_APP_PLAN_0_BASEURL} \
    VUE_APP_PLAN_0_LIMITER=${VUE_APP_PLAN_0_LIMITER} \
    VUE_APP_PLAN_0_CHECKOUT_URL=${VUE_APP_PLAN_0_CHECKOUT_URL} \
    VUE_APP_PLAN_1_NAME=${VUE_APP_PLAN_1_NAME} \
    VUE_APP_PLAN_1_PRICE=${VUE_APP_PLAN_1_PRICE} \
    VUE_APP_PLAN_1_QUOTA=${VUE_APP_PLAN_1_QUOTA} \
    VUE_APP_PLAN_1_BASEURL=${VUE_APP_PLAN_1_BASEURL} \
    VUE_APP_PLAN_1_LIMITER=${VUE_APP_PLAN_1_LIMITER} \
    VUE_APP_PLAN_1_CHECKOUT_URL=${VUE_APP_PLAN_1_CHECKOUT_URL} \
    VUE_APP_APP_URL=${VUE_APP_APP_URL} \
    VUE_APP_SUPPORT_EMAIL=${VUE_APP_SUPPORT_EMAIL}

# build app for production with minification
#RUN npm run build

EXPOSE 8080
#CMD [ "http-server", "dist" ]
ENTRYPOINT ["/bin/sh", "-c" , "npm run build && http-server dist"]